/**
 * @file    config.js
 * @title   OrganTracker dApp — Ethereum Configuration
 * @network Sepolia Testnet
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW TO UPDATE THE CONTRACT ADDRESS
 * ─────────────────────────────────────────────────────────────────────────────
 * Every time you deploy (or redeploy) the OrganTracker contract, Hardhat /
 * Foundry / Remix will print a new contract address in the terminal output,
 * e.g.:
 *
 *   Deployed OrganTracker to: 0xAbCd...1234
 *
 * Steps:
 *   1. Copy that hex address (the full 42-character "0x…" string).
 *   2. Paste it as the value of CONTRACT_ADDRESS below, replacing the
 *      placeholder value that is currently there.
 *   3. Save this file and hard-refresh your browser (Ctrl+Shift+R / Cmd+Shift+R)
 *      so the updated address is picked up by the dApp.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * HOW TO REPLACE THE ABI AFTER REDEPLOYMENT
 * ─────────────────────────────────────────────────────────────────────────────
 * The ABI (Application Binary Interface) describes every function, event, and
 * error the contract exposes.  It is regenerated by the compiler whenever you
 * change and recompile your Solidity source.
 *
 * Where to find the new ABI:
 *   • Hardhat  → artifacts/contracts/OrganTracker.sol/OrganTracker.json
 *                Copy the value of the "abi" key in that JSON file.
 *   • Foundry  → out/OrganTracker.sol/OrganTracker.json  (same structure)
 *   • Remix    → Compilation Details panel → ABI button → copy JSON
 *
 * Steps:
 *   1. Open the generated JSON artifact.
 *   2. Locate the "abi" array (it starts with "[" and contains objects).
 *   3. Select and copy the entire array (brackets included).
 *   4. Replace the CONTRACT_ABI array below with the copied content.
 *   5. Save this file and hard-refresh your browser.
 *
 * ⚠  Always redeploy AND update both CONTRACT_ADDRESS and CONTRACT_ABI
 *    together — a mismatched ABI will cause silent encoding errors that are
 *    extremely hard to debug.
 * ─────────────────────────────────────────────────────────────────────────────
 */

"use strict";

// =============================================================================
// 1.  CONTRACT ADDRESS
//     Replace the string below after every deployment.
// =============================================================================

/**
 * The deployed address of the OrganTracker contract on Sepolia.
 *
 * @type {string}
 * @example "0xAbCdEf0123456789AbCdEf0123456789AbCdEf01"
 */
const CONTRACT_ADDRESS = "0x97e8512186bf6C9901191930F040CBc8676713A9"; // ← paste your deployed address here

// =============================================================================
// 2.  NETWORK — Sepolia Testnet
//     Update only if you migrate to a different network.
// =============================================================================

/**
 * Network configuration for the Ethereum Sepolia testnet.
 *
 * @property {string} name        Human-readable network name shown in the UI.
 * @property {number} chainId     EIP-155 chain identifier.  MetaMask uses this
 *                                to validate that the user is on the correct
 *                                network before submitting transactions.
 * @property {string} rpcUrl      JSON-RPC endpoint used by ethers.js / web3.js
 *                                to read blockchain state without a wallet.
 *                                Swap for your own Alchemy / Infura project URL
 *                                to increase rate limits in production.
 * @property {string} explorerUrl Base URL of the block explorer.  Append a
 *                                transaction hash to deep-link users directly
 *                                to their tx receipt, e.g.:
 *                                  `${NETWORK.explorerUrl}/tx/0xabc…`
 * @property {string} currency    Ticker symbol of the native gas token.
 * @property {number} decimals    Decimal precision of the native gas token.
 */
const NETWORK = {
  name:        "Sepolia Testnet",
  chainId:     11155111,
  rpcUrl:      "https://rpc.sepolia.org",               // public fallback — replace with Alchemy/Infura for prod
  explorerUrl: "https://sepolia.etherscan.io",
  currency:    "ETH",
  decimals:    18,
};

// =============================================================================
// 3.  CONTRACT ABI
//     Replace this array after every recompilation (see file header above).
// =============================================================================

/**
 * ABI for the OrganTracker smart contract.
 *
 * Auto-generated by the Solidity compiler — do not edit by hand.
 * Each entry describes one public function, event, error, or constructor.
 *
 * @type {Array<Object>}
 */
const CONTRACT_ABI = [

  // ── Constructor ────────────────────────────────────────────────────────────
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },

  // ── Custom Errors ──────────────────────────────────────────────────────────
  {
    "type": "error",
    "name": "BoxNotFound",
    "inputs": [{ "name": "boxId", "type": "uint256", "internalType": "uint256" }]
  },
  {
    "type": "error",
    "name": "EmptyOrganType",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotCustodian",
    "inputs": [
      { "name": "boxId",  "type": "uint256", "internalType": "uint256" },
      { "name": "caller", "type": "address", "internalType": "address" }
    ]
  },
  {
    "type": "error",
    "name": "TerminalState",
    "inputs": [
      { "name": "boxId",   "type": "uint256", "internalType": "uint256" },
      { "name": "current", "type": "uint8",   "internalType": "enum OrganTracker.Status" }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddressCustodian",
    "inputs": []
  },

  // ── Events ─────────────────────────────────────────────────────────────────
  {
    "type": "event",
    "name": "BoxCreated",
    "anonymous": false,
    "inputs": [
      { "name": "boxId",     "type": "uint256", "internalType": "uint256", "indexed": true  },
      { "name": "origin",    "type": "address", "internalType": "address", "indexed": true  },
      { "name": "organType", "type": "string",  "internalType": "string",  "indexed": false },
      { "name": "createdAt", "type": "uint256", "internalType": "uint256", "indexed": false }
    ]
  },
  {
    "type": "event",
    "name": "BoxDelivered",
    "anonymous": false,
    "inputs": [
      { "name": "boxId",     "type": "uint256", "internalType": "uint256", "indexed": true  },
      { "name": "custodian", "type": "address", "internalType": "address", "indexed": true  },
      { "name": "timestamp", "type": "uint256", "internalType": "uint256", "indexed": false }
    ]
  },
  {
    "type": "event",
    "name": "CustodianChanged",
    "anonymous": false,
    "inputs": [
      { "name": "boxId",        "type": "uint256", "internalType": "uint256", "indexed": true },
      { "name": "oldCustodian", "type": "address", "internalType": "address", "indexed": true },
      { "name": "newCustodian", "type": "address", "internalType": "address", "indexed": true }
    ]
  },
  {
    "type": "event",
    "name": "TemperatureAlert",
    "anonymous": false,
    "inputs": [
      { "name": "boxId",          "type": "uint256", "internalType": "uint256",                       "indexed": true  },
      { "name": "newTemperature", "type": "int16",   "internalType": "int16",                         "indexed": false },
      { "name": "newStatus",      "type": "uint8",   "internalType": "enum OrganTracker.Status",      "indexed": false }
    ]
  },

  // ── Write Functions ────────────────────────────────────────────────────────
  {
    "type": "function",
    "name": "createBox",
    "stateMutability": "nonpayable",
    "inputs":  [{ "name": "organType", "type": "string",  "internalType": "string"  }],
    "outputs": [{ "name": "boxId",     "type": "uint256", "internalType": "uint256" }]
  },
  {
    "type": "function",
    "name": "checkTemperature",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "boxId",          "type": "uint256", "internalType": "uint256" },
      { "name": "newTemperature", "type": "int16",   "internalType": "int16"   }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "transferCustodian",
    "stateMutability": "nonpayable",
    "inputs": [
      { "name": "boxId",        "type": "uint256", "internalType": "uint256" },
      { "name": "newCustodian", "type": "address", "internalType": "address" }
    ],
    "outputs": []
  },
  {
    "type": "function",
    "name": "confirmDelivery",
    "stateMutability": "nonpayable",
    "inputs":  [{ "name": "boxId", "type": "uint256", "internalType": "uint256" }],
    "outputs": []
  },

  // ── View Functions ─────────────────────────────────────────────────────────
  {
    "type": "function",
    "name": "getBox",
    "stateMutability": "view",
    "inputs":  [{ "name": "boxId", "type": "uint256", "internalType": "uint256" }],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct OrganTracker.OrganBox",
        "components": [
          { "name": "boxId",              "type": "uint256", "internalType": "uint256" },
          { "name": "custodian",          "type": "address", "internalType": "address" },
          { "name": "origin",             "type": "address", "internalType": "address" },
          { "name": "status",             "type": "uint8",   "internalType": "enum OrganTracker.Status" },
          { "name": "currentTemperature", "type": "int16",   "internalType": "int16"   },
          { "name": "organType",          "type": "string",  "internalType": "string"  },
          { "name": "createdAt",          "type": "uint256", "internalType": "uint256" }
        ]
      }
    ]
  },
  {
    "type": "function",
    "name": "getStatus",
    "stateMutability": "view",
    "inputs":  [{ "name": "boxId", "type": "uint256", "internalType": "uint256" }],
    "outputs": [{ "name": "", "type": "uint8", "internalType": "enum OrganTracker.Status" }]
  },
  {
    "type": "function",
    "name": "getCustodian",
    "stateMutability": "view",
    "inputs":  [{ "name": "boxId", "type": "uint256", "internalType": "uint256" }],
    "outputs": [{ "name": "", "type": "address", "internalType": "address" }]
  },
  {
    "type": "function",
    "name": "nextBoxId",
    "stateMutability": "view",
    "inputs":  [],
    "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }]
  }

]; // ← end of ABI — replace everything between the outer brackets after recompile

// =============================================================================
// 4.  EXPORTS — browser-friendly (no bundler required)
//
//     Usage in a plain HTML <script> tag:
//       <script src="config.js"></script>
//       <script>
//         const provider = new ethers.JsonRpcProvider(OrganTrackerConfig.NETWORK.rpcUrl);
//         const contract = new ethers.Contract(
//           OrganTrackerConfig.CONTRACT_ADDRESS,
//           OrganTrackerConfig.CONTRACT_ABI,
//           provider
//         );
//       </script>
//
//     Usage with ES Modules (Vite, Webpack, etc.):
//       import { CONTRACT_ADDRESS, NETWORK, CONTRACT_ABI } from "./config.js";
//
// =============================================================================

/**
 * Named exports — for ES Module bundler environments (Vite, Webpack, Rollup).
 * Tree-shaking will strip anything your app does not import.
 */
export { CONTRACT_ADDRESS, NETWORK, CONTRACT_ABI };

/**
 * Default export — single namespace object for convenience and for plain
 * browser <script> usage via a global variable.
 *
 * When loaded as a classic script the browser exposes:
 *   window.OrganTrackerConfig.CONTRACT_ADDRESS
 *   window.OrganTrackerConfig.NETWORK
 *   window.OrganTrackerConfig.CONTRACT_ABI
 */
const OrganTrackerConfig = { CONTRACT_ADDRESS, NETWORK, CONTRACT_ABI };
export default OrganTrackerConfig;

// Attach to window for non-module browser environments.
if (typeof window !== "undefined") {
  window.OrganTrackerConfig = OrganTrackerConfig;
}
